### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by FalkoJoseph** [Polarbitco/gravitate#7]
- [x] Remove Bower
- [x] Use NPM instead of Bower
- [x] Use eslint for Javascript
- [x] ES6 support with Babel
- [x] Auto download the latest version of Grav
- [x] Auto update the plugins to the latest versions
- [x] Remove Google Analytics tracking code
- [x] Upgrade FontAwesome to v5
- [x] Update installation flow
- [x] Remove `gulp-uglify` and use ES6 minification
- [x] Ability to check/uncheck plugins during installation
- [x] Rename README.md to GRAVITATE.md or add README.md to `.gitignore`

**Comment by JensDebergh** [comment]
So what about the roadmap? Haven't seen any roads being build. Also where are the maps?

**Comment by JensDebergh** [comment]
![spoengebobbe](https://user-images.githubusercontent.com/6651506/41526132-83d123ba-72e3-11e8-9f54-4e1778f4ed21.jpg)
